<h1 class="text-center my-5">Liste de nos annonces</h1>

<p class="text-end">Nous disposons actuellement de <?= $totalAdverts ?> annonces !</p>
<p class="text-end">Seulement <?= $limit ?> sont visibles sur cette page.</p>
<form method="post" action="index.php">
    <label for="selectionLimit">Choix du nombre d'annonces sur cette page :</label>
    <select name="selectionLimit" class="select">
        <option value="5">5</option>
        <option value="10">10</option>
        <option value="15">15</option>
    </select>
    <button class="btn btn-light">Valider</button>
</form>

<?php for($i = 0 ; $i < $limit ; $i++): ?>
<div class="row">
    <div class="col-sm-6 my-4">
        <div class="card">
            <div class="card-header" style="text-transform:uppercase">
            <?= $allAdverts[$i]["type"] ?>
            </div>
            <div class="card-body">
                <h5 class="card-title" style="text-transform:uppercase"><?= htmlspecialchars($allAdverts[$i]["title"]) ?></h5>
                <p class="card-text"><?= nl2br(htmlspecialchars(substr($allAdverts[$i]["description"], 0, 100))) ?>[...]</p>
                <a href="consultAdvert.php?id=<?= $allAdverts[$i]["id"] ?>" class="btn btn-primary">Voir l'annonce</a>
            </div>
        </div>
    </div>
    <?php $i++ ?>
    <?php if($i < $limit): ?>
        <div class="col-sm-6 my-4">
            <div class="card">
                <div class="card-header" style="text-transform:uppercase">
                <?= $allAdverts[$i]["type"] ?>
                </div>
                <div class="card-body">
                    <h5 class="card-title" style="text-transform:uppercase"><?= htmlspecialchars($allAdverts[$i]["title"]) ?></h5>
                    <p class="card-text"><?= nl2br(htmlspecialchars(substr($allAdverts[$i]["description"], 0, 100))) ?>[...]</p>
                    <a href="consultAdvert.php?id=<?= $allAdverts[$i]["id"] ?>" class="btn btn-primary">Voir l'annonce</a>
                </div>
            </div>
        </div>
    <?php endif ?>
</div>
<?php endfor ?>